<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"旅行社管理",
			            "menuJump":"列表",
			            "tableName":"lvxingshe"
			        }
			    ],
			    "menu":"旅行社管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"旅行团信息管理",
			            "menuJump":"列表",
			            "tableName":"lvxingtuan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"旅行团信息订单管理",
			            "menuJump":"列表",
			            "tableName":"lvxingtuanOrder"
			        }
			    ],
			    "menu":"旅行团信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"酒店管理",
			            "menuJump":"列表",
			            "tableName":"jiudian"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
							"修改",
			                "删除"
			            ],
			            "menu":"酒店留言管理",
			            "menuJump":"列表",
			            "tableName":"jiudianLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"酒店订单管理",
			            "menuJump":"列表",
			            "tableName":"jiudianOrder"
			        }
			    ],
			    "menu":"酒店管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"车票管理",
			            "menuJump":"列表",
			            "tableName":"chepiao"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"车票订单管理",
			            "menuJump":"列表",
			            "tableName":"chepiaoOrder"
			        }
			    ],
			    "menu":"车票管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"商品信息管理",
			            "menuJump":"列表",
			            "tableName":"shangpin"
			        }
			    ],
			    "menu":"商品信息管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"酒店星级管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJiudian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"新闻类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商品类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShangpin"
                    }

                ],
                "menu":"基础数据管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"新闻管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"新闻管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"旅行团信息管理",
			            "menuJump":"列表",
			            "tableName":"lvxingtuan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"旅行团信息订单管理",
			            "menuJump":"列表",
			            "tableName":"lvxingtuanOrder"
			        }
			    ],
			    "menu":"旅行团信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改"
			            ],
			            "menu":"商品信息管理",
			            "menuJump":"列表",
			            "tableName":"shangpin"
			        }
			    ],
			    "menu":"商品信息管理"
			}
	    
			
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"新闻管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"新闻管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"旅行社",
	    "tableName":"lvxingshe"
	}
	,
	{
	    "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"旅行团信息管理",
			            "menuJump":"列表",
			            "tableName":"lvxingtuan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"旅行团信息订单管理",
			            "menuJump":"列表",
			            "tableName":"lvxingtuanOrder"
			        }
			    ],
			    "menu":"旅行团信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"酒店管理",
			            "menuJump":"列表",
			            "tableName":"jiudian"
			        }
			        ,
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"酒店留言管理",
			            "menuJump":"列表",
			            "tableName":"jiudianLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"酒店订单管理",
			            "menuJump":"列表",
			            "tableName":"jiudianOrder"
			        }
			    ],
			    "menu":"酒店管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"车票管理",
			            "menuJump":"列表",
			            "tableName":"chepiao"
			        }
			        ,
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"车票订单管理",
			            "menuJump":"列表",
			            "tableName":"chepiaoOrder"
			        }
			    ],
			    "menu":"车票管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"商品信息管理",
			            "menuJump":"列表",
			            "tableName":"shangpin"
			        }
			    ],
			    "menu":"商品信息管理"
			}
	      
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"新闻管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"新闻管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
